### PR TITLE
Feature fix organisation unit descendant pull

### LINKED ISSUE #275: 2nd login doesn't retrieve the user OU tree
A quick login-logout-login test demonstrates that either in the login or the logout process, something's going wrong regarding the downloaded OUs. The first pull downloads both the OU directly assigned to the user and the descendants, while subsequent logins after a logout, only retrieve the directly assigned ones.

### PR DESCRIPTION
**Pull request by idelcano**
Closes #275

### CODE REVIEW

File: core/src/androidTest/java/org/hisp/dhis/android/core/LogoutCallMockIntegrationShould.java [hunk 1]
```diff
@@ -0,0 +1,113 @@
...
+        givenAEventInDatabase();
+
+        Truth.assertThat(isDatabaseEmpty()).isFalse();
+
+        d2.logOut().call();
+
+        Truth.assertThat(isDatabaseEmpty()).isTrue();
+    }
+
+    private boolean isDatabaseEmpty() {
```
Comment (xurxodev) [inline core/src/androidTest/java/org/hisp/dhis/android/core/LogoutCallMockIntegrationShould.java]: duplicated method, please can you move this method to the base class?

File: core/src/androidTest/java/org/hisp/dhis/android/core/LogoutCallRealIntegrationShould.java [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+        eventCall.call();
+
+        Truth.assertThat(isDatabaseEmpty()).isFalse();
+
+        d2.logOut().call();
+
+        Truth.assertThat(isDatabaseEmpty()).isTrue();
+    }
+
+    private boolean isDatabaseEmpty() {
```
Comment (xurxodev) [inline core/src/androidTest/java/org/hisp/dhis/android/core/LogoutCallRealIntegrationShould.java]: duplicated method, please can you move this method to the base class?

File: core/src/main/java/org/hisp/dhis/android/core/configuration/ConfigurationStoreImpl.java [hunk 3]
```diff
@@ -35,11 +35,12 @@
 import android.support.annotation.Nullable;
 
 import org.hisp.dhis.android.core.data.database.DatabaseAdapter;
+import org.hisp.dhis.android.core.common.DeletableStore;
 
 import static org.hisp.dhis.android.core.utils.StoreUtils.sqLiteBind;
 import static org.hisp.dhis.android.core.utils.Utils.isNull;
 
-public class ConfigurationStoreImpl implements ConfigurationStore {
+public class ConfigurationStoreImpl implements ConfigurationStore, DeletableStore {
```
Comment (xurxodev) [inline core/src/main/java/org/hisp/dhis/android/core/configuration/ConfigurationStoreImpl.java]: Store interfaces should extend from DeletableStore, for avoid duplicate code between interfaces because there are stores as OrganisationUnitStore with delete method also

**Review by xurxodev — CHANGES_REQUESTED** [review]
@idelcano I have found some problems to review and
unit tests execution does not compile, please before realize push execute all tests.
- I think that It's necessary a test that verifies the initial problem according to issue description "A quick login-logout-login test demonstrates that either in the login or the logout process, something's going wrong regarding the downloaded OUs. The first pull downloads both the OU directly assigned to the user and the descendants, while subsequent logins after a logout, only retrieve the directly assigned ones."

File: core/src/androidTest/java/org/hisp/dhis/android/core/data/database/AbsStoreTestCase.java [hunk 4]
```diff
@@ -41,11 +43,15 @@
 public abstract class AbsStoreTestCase {
     private SQLiteDatabase sqLiteDatabase;
     private DatabaseAdapter databaseAdapter;
+    private String dbName = "test2.db";
 
     @Before
     public void setUp() throws IOException {
+        if(dbName!=null){
```
Comment (xurxodev) [inline core/src/androidTest/java/org/hisp/dhis/android/core/data/database/AbsStoreTestCase.java]: @idelcano create a physical database and remove on every test convert test execution slower, really is physical database necessary? It's slower because is necessary access to the disk to remove on every test and for every query access to disk also, in-memory database is faster.

**Review by xurxodev — CHANGES_REQUESTED** [review]

File: core/src/androidTest/java/org/hisp/dhis/android/core/data/database/AbsStoreTestCase.java (hunk 4 above)
Comment (idelcano) [reply core/src/androidTest/java/org/hisp/dhis/android/core/data/database/AbsStoreTestCase.java]: @xurxodev i think it is useful and only checks if db variable is null in the normal tests. 

The database will removed only if exist, this not happen in the normal tests. 
But If you want test using a db name (for example for pull the database in the middle of the test) is necessary remove it before/after every test to be sure the database is new.
I added it because i have a lot of false failing tests in some situations after added a db name to pull it.

**Review by xurxodev — APPROVED** [review]
thanks @idelcano. I have done refactors, when you have time review it and let me know if you have any questions.
